### ISSUE TITLE
selenium driver cant open in docker container 

### ISSUE THREAD

**Issue by Gwyn-The-Human** [Gwyn-The-Human/Data-Collection-Pipeline#1]
its all in the title; scraper can't run because chrome failed to start; I think its probably a problem with how ive installed chrome and chrome driver in Dockerfile but can't work out what exactly. 

``` 
[WDM] - Downloading: 100%|██████████| 7.26M/7.26M [00:00<00:00, 13.1MB/s]
scraper/scraper_main.py:39: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  self.driver = webdriver.Chrome(ChromeDriverManager().install(), options=option)
Traceback (most recent call last):
  File "scraper/scraper_main.py", line 252, in <module>
    my_scraper = Scraper()
  File "scraper/scraper_main.py", line 39, in __init__
    self.driver = webdriver.Chrome(ChromeDriverManager().install(), options=option)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x564b8b6fb463 <unknown>
```

**Comment by lukebelliveau** [comment]
@Gwyn-The-Human You're expecting X to happen when you do Y, but I don't know what X or Y are. Can you leave a message with the following info:

**system info**

**What I expect to happen**

**What is happening**

**Steps to reproduce**

## example
Here's mine _(I took a guess that you're trying to build the image, I got a different error):_
I can't build the image. This may be because I'm on an ARM processor (Mac M1), but here's an example of what I need to see from you anyway:

**system info**
I am running this locally on my M1 Mac, using Docker Desktop.

**What I expect to happen**
running `docker build .` from the root of the project should build the docker image based on your Dockerfile

**What is happening**
`docker build` fails: when trying to install Chrome:
```bash
 > [4/4] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'     && apt-get -y update     && apt-get install -y google-chrome-stable     && wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip     && apt-get install -yqq unzip     && unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/:
#8 0.192 Warning: apt-key output should not be parsed (stdout is not a terminal)
#8 0.885 OK
#8 0.936 Hit:1 http://deb.debian.org/debian buster InRelease
#8 0.939 Hit:2 http://deb.debian.org/debian-security buster/updates InRelease
#8 0.949 Hit:3 http://deb.debian.org/debian buster-updates InRelease
#8 1.205 Get:4 http://dl.google.com/linux/chrome/deb stable InRelease [1811 B]
#8 1.305 Get:5 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1107 B]
#8 1.313 Fetched 2918 B in 0s (7234 B/s)
#8 1.313 Reading package lists...
#8 1.659 Reading package lists...
#8 1.998 Building dependency tree...
#8 2.057 Reading state information...
#8 2.100 E: Unable to locate package google-chrome-stable
------
executor failed running [/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'     && apt-get -y update     && apt-get install -y google-chrome-stable     && wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip     && apt-get install -yqq unzip     && unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/]: exit code: 100
```

**Steps to reproduce**
_again, this is probably because i'm on an ARM processor, so don't try to fix this - just making an example issue for you to follow._
`$ git clone https://github.com/Gwyn-The-Human/Data-Collection-Pipeline.git`
`$ docker build .`

**Comment by lukebelliveau** [comment]
## more practical answer:

the key issue is here: googling this line comes up with some interesting results on SO (seems like it may be an issue with permissions, which are always tricky..

`selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)`

## guessing:
this is probably bad advice, I'm making barely-educated guesses that I'm unable to test myself:

A prevailing solution I see is that it's a permissions issue, which will be bypassed with the `--no-sandbox` flag in the Chrome Webdriver. [Only use this to confirm it's a permissions issue, do not just proceed with this if it works- it's dangerous](https://stackoverflow.com/questions/50790733/unknown-error-devtoolsactiveport-file-doesnt-exist-error-while-executing-selen/50791503#50791503).

I'm totally guessing here (I don't use much python and haven't scripted Selenium stuff with python before), but you might be able to find something in the link below. If the `--no-sandbox` thing works, at least you know that it's a permissions issue. Then we figure out how to fix your permissions:

- lots of stuff: https://stackoverflow.com/questions/50790733/unknown-error-devtoolsactiveport-file-doesnt-exist-error-while-executing-selen/50791503#50791503
- setting `--no-sandbox`: https://stackoverflow.com/a/47078460/3124493

maybe this belongs somewhere in the `options` you pass to `webdriver.Chrome`? maybe not? try changing this:

https://github.com/Gwyn-The-Human/Data-Collection-Pipeline/blob/748b2563c87bfb599d74e9f30ee6b9fba22a920c/scraper/scraper_main.py#L37-L39

to this:

```py
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')

#sets up driver, prepares raw data folder and df_batch list
        self.driver = webdriver.Chrome(ChromeDriverManager().install(), options=option, chrome_options=chrome_options)
```

(recklessly stolen from [here](https://stackoverflow.com/questions/47074208/chrome-fails-to-load-with-python-selenium-chromedriver/47078460#47078460))

**Comment by Gwyn-The-Human** [comment]
Got it! 

Its not really for use by others anyway because the functionality of the docker file is less than the code in the github repo so I'll just take the practice with docker and leave it as is with the --no-sandbox flag.
